//
// This file is automatically generated by Facc
// https://github.com/fawdlstty/Fapp
//



#ifndef __FUNC_EXPR_AST_HPP__
#define __FUNC_EXPR_AST_HPP__



#include <iostream>
#include <memory>
#include <optional>
#include <string>
#include <string_view>

#include <fmt/core.h>

#include <Facc/IEnumerator.hpp>
#include <Facc/Parser/IAST.h>
#include <Facc/Parser/AstParser.hpp>



class FuncArgsAST;
class SAST;

class FuncExprAST: IAST {
public:
	// func_expr ::= '(' func_args ')' s '{}'

	std::shared_ptr<AstParser> Parser;

	IEnumerator<int> TryParse (int _pos) override {
		if (!Parser->TryReg ("FuncExprAST", _pos))
			co_return;
		auto _0_enum = _try_parse_0 (_pos);
		while (_0_enum.MoveNext ()) {
			auto _1_enum = _try_parse_1 (_0_enum.Current);
			while (_1_enum.MoveNext ()) {
				auto _2_enum = _try_parse_2 (_1_enum.Current);
				while (_2_enum.MoveNext ()) {
					auto _3_enum = _try_parse_3 (_2_enum.Current);
					while (_3_enum.MoveNext ()) {
						auto _4_enum = _try_parse_4 (_3_enum.Current);
						while (_4_enum.MoveNext ()) {
							co_yield _4_enum.Current;
						}
					}
				}
			}
		}
		Parser->UnReg ("FuncExprAST", _pos);
	}

	IEnumerator<int> _try_parse_0 (int _pos);
	IEnumerator<int> _try_parse_1 (int _pos);
	IEnumerator<int> _try_parse_2 (int _pos);
	IEnumerator<int> _try_parse_3 (int _pos);
	IEnumerator<int> _try_parse_4 (int _pos);
	bool IsValid () override;
	void PrintTree (int _indent);
	int size ();

	std::string Value_0 = "";
	std::shared_ptr<FuncArgsAST> Value_1 = nullptr;
	std::string Value_2 = "";
	std::shared_ptr<SAST> Value_3 = nullptr;
	std::string Value_4 = "";
};



#include "FuncArgsAST.hpp"
#include "SAST.hpp"



inline bool FuncExprAST::IsValid () {
	return (Value_0.size () > 0 && (Value_1 != nullptr && Value_1->IsValid ()) && Value_2.size () > 0 && (Value_3 != nullptr && Value_3->IsValid ()) && Value_4.size () > 0);
}

inline void FuncExprAST::PrintTree (int _indent) {
	std::cout << std::string ((_indent + 1) * 4, ' ') << '[' << Value_0 << ']' << std::endl;
	if (Value_1 && Value_1->IsValid ()) {
		Value_1->PrintTree (_indent + 1);
	}
	std::cout << std::string ((_indent + 1) * 4, ' ') << '[' << Value_2 << ']' << std::endl;
	if (Value_3 && Value_3->IsValid ()) {
		Value_3->PrintTree (_indent + 1);
	}
	std::cout << std::string ((_indent + 1) * 4, ' ') << '[' << Value_4 << ']' << std::endl;
}

inline int FuncExprAST::size () {
	int _len = 0;
	_len += Value_0.size ();
	_len += Value_1->size ();
	_len += Value_2.size ();
	_len += Value_3->size ();
	_len += Value_4.size ();
	return _len;
}
inline IEnumerator<int> FuncExprAST::_try_parse_0 (int _pos) {
	Parser->SetErrorPos (_pos);
	if (Parser->TryMatchString (_pos, "(")) {
		Value_0 = "(";
		co_yield _pos + Value_0.size ();
		Value_0 = "";
	}
}

inline IEnumerator<int> FuncExprAST::_try_parse_1 (int _pos) {
	Parser->SetErrorPos (_pos);
	auto _o = std::make_shared<FuncArgsAST> ();
	_o->Parser = Parser;
	auto _enum = _o->TryParse (_pos);
	while (_enum.MoveNext ()) {
		Value_1 = _o;
		co_yield _enum.Current;
		Value_1 = nullptr;
	}
}

inline IEnumerator<int> FuncExprAST::_try_parse_2 (int _pos) {
	Parser->SetErrorPos (_pos);
	if (Parser->TryMatchString (_pos, ")")) {
		Value_2 = ")";
		co_yield _pos + Value_2.size ();
		Value_2 = "";
	}
}

inline IEnumerator<int> FuncExprAST::_try_parse_3 (int _pos) {
	Parser->SetErrorPos (_pos);
	auto _o = std::make_shared<SAST> ();
	_o->Parser = Parser;
	auto _enum = _o->TryParse (_pos);
	while (_enum.MoveNext ()) {
		Value_3 = _o;
		co_yield _enum.Current;
		Value_3 = nullptr;
	}
}

inline IEnumerator<int> FuncExprAST::_try_parse_4 (int _pos) {
	Parser->SetErrorPos (_pos);
	if (Parser->TryMatchString (_pos, "{}")) {
		Value_4 = "{}";
		co_yield _pos + Value_4.size ();
		Value_4 = "";
	}
}



#endif // __FUNC_EXPR_AST_HPP__
